{
    "name": "Photostudio Connector",
    "summary": "Catalog photos from the garment you already shot. Ghost, on-model, lifestyle, and more, written back to the product.",
    "images": ["static/description/banner.png"],
    "version": "20.0.1.0.0",
    "category": "Sales/Sales",
    "author": "Photostudio",
    "website": "https://photostudio.io",
    "support": "peter@photostudio.io",
    "license": "LGPL-3",
    "depends": ["product"],
    "data": [
        "security/photostudio_security.xml",
        "security/ir.model.access.csv",
        "data/ir_cron.xml",
        "views/photostudio_job_views.xml",
        "views/res_config_settings_views.xml",
        "views/product_template_views.xml",
        "views/photostudio_generate_wizard_views.xml",
        "views/photostudio_menus.xml",
    ],
    "post_init_hook": "post_init_hook",
    "application": True,
    "installable": True,
}
